apiVersion: v1
kind: Service
metadata:
  name: triton-vitpose-service
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  selector:
    app: triton-vitpose
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: http2
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: metrics
      protocol: TCP
      port: 8002
      targetPort: 8002
  externalTrafficPolicy: Cluster